# app/config/routing.yml

# Dans la clé app, la déclaration a été changée pour dire à Symfony de ne plus charger nos contrôleurs REST, la clé
# app.resource passe ainsi de @AppBundle/Controller à @AppBundle/Controller/DefaultController.php

app:
    resource: '@AppBundle/Controller/DefaultController.php'
    type: annotation

places:
    type: rest
    resource: AppBundle\Controller\PlaceController

prices:
    type: rest
    resource: AppBundle\Controller\Place\PriceController

themes:
    type: rest
    resource: AppBundle\Controller\Place\ThemeController

users:
    type: rest
    resource: AppBundle\Controller\UserController

preferences:
    type: rest
    resource: AppBundle\Controller\User\PreferenceController

suggestions:
    type: rest
    resource: AppBundle\Controller\UserController

budget:
    type: rest
    resource: AppBundle\Controller\User\BudgetController

auth-tokens:
    type: rest
    resource: AppBundle\Controller\AuthTokenController