# app/config/security.yml

# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded

    # => activer le firewall de Symfony et le configurer avec notre fournisseur
    # d’utilisateurs et le listener que nous venons de créer.
    providers:
        auth_token_user_provider:
            id: auth_token_user_provider
        in_memory:
            memory: ~

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
#        Pattern trouvé à https://stackoverflow.com/questions/32515191/symfony2-authenticate-users-with-api-key-access-control-issue
            pattern: /v(\d+\.?\d*)/(?!users)
#            Pourquoi dans tuto: ^/ seulement !!!!!!!!!!! ???????????? todo voir Pattern
            stateless: true
            # stateless: true => À chaque requête, l’identité de l’utilisateur est revérifiée.
            # La session n’est jamais utilisée.
            simple_preauth:
                authenticator: auth_token_authenticator
            provider: auth_token_user_provider
            anonymous: ~

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            #http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            #form_login: ~

    # Ajout d'un encoder pour l'entité User
    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
