# src/AppBundle/Resources/config/validation.yml

AppBundle\Entity\Place:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: name
    properties:
        name:
            - NotBlank: ~
            - Type: string
        address:
            - NotBlank: ~
            - Type: string
# => Ajouter la contrainte UniqueEntity "name" en annotation dans l'Entity Place

AppBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: email
    properties:
        firstname:
            - NotBlank: ~
            - Type: string
        lastname:
            - NotBlank: ~
            - Type: string
        email:   # => On ajoute la contrainte UniqueEntity "email" en annotation dans l'Entity User
            - NotBlank: ~
            - Email: ~
        plainPassword: #validation de base pour le mot de passe
            - NotBlank: { groups: [New, FullUpdate] }
            - Type: string
            - Lenght:
                min: 3
                max: 50
#        !!! Champ plainPassword => Les groupes permettrons d’activer sa contrainte
#        NotBlank lorsque le client voudra créer ou mettre à jour tous les champs de l’utilisateur.
#        Mais lors d’une mise à jour partielle (PATCH), si le champ est nul, il sera ignoré.
# !!!!! le mdp ne doit pas être SERIALISE (-> pas associé à un groupe de sérialisation)!!!!!

# Règles de validation pour la création d'un prix
AppBundle\Entity\Price:
    properties:
        type:
            - NotNull: ~
            - Choice:
                choices: [less_than_12, for_all]
        value:
            - NotNull: ~
            - Type: numeric
            - GreaterThanOrEqual:
                value: 0

# Règles de validation pour la création d'un thème
AppBundle\Entity\Theme:
    properties:
        name:
            - NotNull: ~
            - Choice:
                choices: [ art, architecture, history, science-fiction, sport ]
        value:
            - NotNull: ~
            - Type: float
            - GreaterThan:
                value: 0
            - LessThanOrEqual:
                value: 10

# Règles de validation pour la création d'une préférence
AppBundle\Entity\Preference:
    properties:
        name:
            - NotNull: ~
            - Choice:
                choices: [ art, architecture, history, science-fiction, sport ]
        value:
            - NotNull: ~
            - Type: numeric
            - GreaterThan:
                value: 0
            - LessThanOrEqual:
                value: 10

# Règles de validation pour la création d'un budget
AppBundle\Entity\Budget:
    properties:
        scope:
            - NotNull: ~
            - Choice:
                choices: [ less_than_10, between_10_25, more_than_25 ]
        value:
            - NotNull: ~
            - Type: numeric
            - GreaterThan:
                value: 0

# Règles de validation pour la création de Credentials


